stages:
  - build
  - deploy

variables:
  IMAGE_TAG: levonsargsyan1990/lensman-coming-soon

before_script:
  - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

deploy:
  stage: deploy
  image: gitlab/dind:latest
  environment: production
  only:
    - master
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOYMENT_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - ssh root@$DEPLOYMENT_SERVER_IP "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker stop lensman-coming-soon || true && docker rm lensman-coming-soon || true; docker pull ${IMAGE_TAG}:latest; docker run -d -p 8000:3000 --name lensman-coming-soon ${IMAGE_TAG}"
